/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Analysis {
  analysis_type: string;
  created_by: string | null;
  data: Json;
  deleted_at: Timestamp | null;
  generated_at: Generated<Timestamp | null>;
  id: Generated<string>;
  insights: string[] | null;
  project_id: string | null;
  sprint_id: string | null;
  summary: string | null;
}

export interface Backlog {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  name: string;
  priority: Generated<number | null>;
  project_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Metrics {
  deleted_at: Timestamp | null;
  id: Generated<string>;
  metadata: Json | null;
  metric_name: string;
  metric_type: string;
  project_id: string | null;
  recorded_at: Generated<Timestamp | null>;
  sprint_id: string | null;
  task_id: string | null;
  unit: string | null;
  value: Numeric;
}

export interface Project {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: string | null;
  icon_url: string | null;
  id: Generated<string>;
  key: string;
  name: string;
  owner_id: string | null;
  status: Generated<string | null>;
  task_counter: Generated<number | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface Sprint {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  end_date: Timestamp | null;
  goal: string | null;
  id: Generated<string>;
  name: string;
  project_id: string;
  start_date: Timestamp | null;
  status: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface SprintSchedule {
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  duration_minutes: number | null;
  event_type: string;
  id: Generated<string>;
  is_completed: Generated<boolean | null>;
  location: string | null;
  notes: string | null;
  scheduled_date: Timestamp;
  sprint_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface Task {
  actual_hours: Numeric | null;
  assignee_id: string | null;
  backlog_id: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  description: string | null;
  due_date: Timestamp | null;
  estimated_hours: Numeric | null;
  id: Generated<string>;
  parent_task_id: string | null;
  priority: Generated<string | null>;
  project_id: string;
  reporter_id: string | null;
  sprint_id: string | null;
  status: Generated<string | null>;
  story_points: number | null;
  tags: Generated<string[] | null>;
  task_key: string | null;
  task_type: Generated<string | null>;
  title: string;
  updated_at: Generated<Timestamp | null>;
}

export interface User {
  avatar_url: string | null;
  created_at: Generated<Timestamp | null>;
  deleted_at: Timestamp | null;
  email: string;
  full_name: string | null;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  password_hash: string;
  role: Generated<string | null>;
  updated_at: Generated<Timestamp | null>;
  username: string;
}

export interface DB {
  analysis: Analysis;
  backlog: Backlog;
  metrics: Metrics;
  project: Project;
  sprint: Sprint;
  sprint_schedule: SprintSchedule;
  task: Task;
  user: User;
}
