/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AvailabilityStatus = "approved" | "pending" | "rejected";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type PokerSessionStatus = "completed" | "revealed" | "voting";

export type SprintStatus = "active" | "closed" | "completed" | "planned";

export type SubscriptionTier = "enterprise" | "free" | "pro";

export type TaskPriority = "critical" | "high" | "low" | "medium";

export type TaskStatus = "done" | "in_progress" | "review" | "test" | "to_do";

export type TaskType = "bug" | "epic" | "spike" | "story" | "task";

export type TeamRole = "admin" | "member" | "viewer";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Backlog {
  backlog_id: Generated<string>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  name: string;
  project_id: string;
  updated_at: Generated<Timestamp>;
}

export interface BurndownData {
  burndown_id: Generated<string>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  entry_date: Timestamp;
  ideal_points: number;
  metrics_id: string;
  remaining_points: number;
  updated_at: Generated<Timestamp>;
}

export interface Organization {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  name: string;
  organization_id: Generated<string>;
  subscription_tier: Generated<SubscriptionTier>;
  updated_at: Generated<Timestamp>;
}

export interface PokerSession {
  created_at: Generated<Timestamp>;
  created_by: string;
  deleted_at: Timestamp | null;
  final_estimate: number | null;
  session_id: Generated<string>;
  sprint_id: string;
  status: Generated<PokerSessionStatus>;
  task_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PokerVote {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  session_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  vote_id: Generated<string>;
  vote_value: number;
}

export interface Project {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  icon_url: string | null;
  key: string;
  name: string;
  organization_id: string;
  owner_id: string | null;
  project_id: Generated<string>;
  status: Generated<string | null>;
  task_counter: Generated<number | null>;
  team_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Generated<Timestamp>;
  userAgent: string | null;
  userId: string;
}

export interface Sprint {
  completed_points: Generated<number>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  end_date: Timestamp;
  name: string;
  project_id: string;
  sprint_id: Generated<string>;
  start_date: Timestamp;
  status: Generated<SprintStatus>;
  total_points: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface SprintAvailability {
  approved_at: Timestamp | null;
  approved_by: string | null;
  availability_id: Generated<string>;
  availability_pattern: Json;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  half_days: Generated<number>;
  notes: string | null;
  off_days: number;
  sprint_id: string;
  status: Generated<AvailabilityStatus>;
  submitted_at: Generated<Timestamp | null>;
  submitted_by: string;
  total_hours: Numeric;
  updated_at: Generated<Timestamp>;
  user_id: string;
  working_days: number;
}

export interface SprintMetrics {
  completed_points: Generated<number>;
  completed_tasks: Generated<number>;
  completion_percentage: Generated<Numeric | null>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  metrics_id: Generated<string>;
  sprint_id: string;
  total_points: Generated<number>;
  total_tasks: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Task {
  assignee_id: string | null;
  backlog_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  due_date: Timestamp | null;
  estimated_hours: number | null;
  priority: Generated<TaskPriority>;
  project_id: string;
  reporter_id: string;
  sprint_id: string | null;
  status: Generated<TaskStatus>;
  story_points: number | null;
  tags: Generated<string[] | null>;
  task_id: Generated<string>;
  task_key: string | null;
  task_type: Generated<TaskType>;
  time_taken_to_complete: number | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Team {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  lead_user_id: string | null;
  name: string;
  organization_id: string;
  team_id: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TeamMembership {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  membership_id: Generated<string>;
  role_in_team: Generated<TeamRole>;
  team_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  first_name: string | null;
  id: string;
  image: string | null;
  is_active: Generated<boolean | null>;
  last_name: string | null;
  name: string;
  organization_id: string | null;
  role: Generated<string | null>;
  updatedAt: Generated<Timestamp>;
}

export interface UserAnalytics {
  analytics_id: Generated<string>;
  bugs_fixed: Generated<number>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  hours_available: Generated<Numeric>;
  hours_logged: Generated<Numeric>;
  sprint_id: string;
  stories_completed: Generated<number>;
  total_story_points: Generated<number>;
  updated_at: Generated<Timestamp>;
  user_id: string;
  utilization_rate: Generated<Numeric | null>;
}

export interface VelocityData {
  committed_points: number;
  completed_points: number;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  metrics_id: string;
  sprint_number: number;
  updated_at: Generated<Timestamp>;
  velocity: Generated<Numeric | null>;
  velocity_id: Generated<string>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  backlog: Backlog;
  burndown_data: BurndownData;
  organization: Organization;
  poker_session: PokerSession;
  poker_vote: PokerVote;
  project: Project;
  session: Session;
  sprint: Sprint;
  sprint_availability: SprintAvailability;
  sprint_metrics: SprintMetrics;
  task: Task;
  team: Team;
  team_membership: TeamMembership;
  user: User;
  user_analytics: UserAnalytics;
  velocity_data: VelocityData;
  verification: Verification;
}
