// Likely will be auto generated by the database, this is just an example
import { EPriority, ETaskStatus } from '@/config/enums';

export interface Task {
  id: string;
  title: string;
  description: string;
  priority: EPriority;
  status: ETaskStatus;
  assigneeId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface TaskCreateInput {
  title: string;
  description?: string;
  priority?: EPriority;
  assigneeId?: string | null;
}
